@protocol=http
@host=localhost
@port=8000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzIyOTM3MDY4LCJpYXQiOjE3MjI5MzM0NjgsImp0aSI6IjhkMDg4ZDRlZjVlOTRkMjJhODEzMTkxMDE4NTJkZmEwIiwidXNlcl9pZCI6Mn0.d6BGhU-x47OSQdnqGcpLt02KhERkyAatWqBpFdhf-Yw
######
GET {{protocol}}://{{host}}:{{port}}/api/ HTTP/1.1

######
GET {{protocol}}://{{host}}:{{port}}/api/items HTTP/1.1
Authorization: Bearer {{token}}

########

POST {{protocol}}://{{host}}:{{port}}/api/items/ HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{"name": "De Prueba 2", "description": "Descripción 2"}
####

GET http://localhost:3002/api HTTP/1.1

#######
GET http://localhost:3002/api/volunteer/6090907r HTTP/1.1
####
# LOGIN ================================================
POST {{protocol}}://{{host}}:{{port}}/auth/login/ HTTP/1.1
Content-Type: application/json

{"email": "cmarchena@gmail.com", "password": "1234"}

####

POST {{protocol}}://{{host}}:{{port}}/auth/register/ HTTP/1.1
Content-Type: application/json

{"email": "testcmarchena@gmail.com", "password": 1234}

####

GET {{protocol}}://{{host}}:{{port}}/api/items HTTP/1.1
Authorization: Bearer {{token}}
####

POST {{protocol}}://{{host}}:{{port}}/auth/token/refresh/ HTTP/1.1
Content-Type: application/json

{"email": "cmarchena@gmail.com", "password": 1234}
######
GET {{protocol}}://{{host}}:{{port}}/auth/users
Authorization: Bearer {{token}}


####
# ====== PRODUCTS
GET {{protocol}}://{{host}}:{{port}}/inventory/products
Authorization: Bearer {{token}}

######
GET {{protocol}}://{{host}}:{{port}}/inventory/products/1
Authorization: Bearer {{token}}

######

POST  {{protocol}}://{{host}}:{{port}}/inventory/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ean": "812341234",
    "name": "Product 1",
    "description": "Bread",
    "category": "Dairy",
    "unit_of_measure": "kilogram"
}