# Generated by Django 4.2.14 on 2024-08-13 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='reception_batch',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
