# Generated by Django 4.2.14 on 2024-08-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='best_before_date',
        ),
    ]
