# Generated by Django 4.2.14 on 2024-08-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='storefront_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warehouse_quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
