# Generated by Django 4.2.14 on 2024-08-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_receptionbatch_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
